{**
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey
 *}

{
  ref:
	    https://www.Nim.org/manual/5.1/manual.html
      https://www.Nim.org/manual/5.3/manual.html
}

  sNimKeywords =
    'addr,'+
    'and,'+
    'as,'+
    'asm,'+
    'bind,'+
    'block,'+
    'break,'+
    'case,'+
    'cast,'+
    'concept,'+
    'const,'+
    'continue,'+
    'converter,'+
    'defer,'+
    'discard,'+
    'distinct,'+
    'div,'+
    'do,'+
    'elif,'+
    'else,'+
    'end,'+
    'enum,'+
    'except,'+
    'export,'+
    'finally,'+
    'for,'+
    'from,'+
    'func,'+
    'if,'+
    'import,'+
    'in,'+
    'include,'+
    'interface,'+
    'is,'+
    'isnot,'+
    'iterator,'+
    'let,'+
    'macro,'+
    'method,'+
    'mixin,'+
    'mod,'+
    'not,'+
    'notin,'+
    'object,'+
    'of,'+
    'or,'+
    'out,'+

    'proc,'+
    'ptr,'+
    'raise,'+
    'ref,'+
    'return,'+
    'shl,'+
    'shr,'+
    'static,'+
    'template,'+

    'try,'+
    'type,'+
    'using,'+
    'var,'+
    'when,'+
    'while,'+

    'xor,'+
    'yield,'+
    'range,'+
		'array,'+
		'seq,'+
		'set,'+
		'pointer,'+
		'tuple';

  sNimTypes =
    'uint,'+
		'int,'+
    'int8,'+
    'int16,'+
    'int32,'+
    'int64,'+
		'cint,'+
		'float,'+
		'float32,'+
		'float64),'+
		'bool,'+
		'string,'+
		'auto,'+
		'cstring,'+
		'char,'+
		'byte,'+
		'tobject,'+
		'typedesc,'+
		'stmt,'+
		'expr,'+
		'any,'+
		'untyped,'+
		'typed,'+
    'openArray,'+
		'varargs,'+
		'void';

  sNimValues =
    'true,'+
		'false,'+
		'Inf,'+
		'NegInf,'+
		'NaN,'+
		'nil';

  sNimFunctions =
    'new,'+
		'await,'+
		'assert,'+
		'echo,'+
		'defined,'+
		'declared,'+
		'newException,'+
		'countup,'+
		'countdown,'+
		'high,'+
		'low,'+
		'ord,'+
		'chr,'+
		'inc,'+
		'dec,'+
		'succ,'+
		'pred';


