{**
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey
 *}

{
  ref: https://www.Nim.org/manual/5.1/manual.html
       https://www.Nim.org/manual/5.3/manual.html
}

  sNimKeywords =
    'addr,'+
    'and,'+
    'as,'+
    'asm,'+
    'bind,'+
    'block,'+
    'break,'+
    'case,'+
    'cast,'+
    'concept,'+
    'const,'+
    'continue,'+
    'converter,'+
    'defer,'+
    'discard,'+
    'distinct,'+
    'div,'+
    'do,'+
    'elif,'+
    'else,'+
    'end,'+
    'enum,'+
    'except,'+
    'export,'+
    'finally,'+
    'for,'+
    'from,'+
    'func,'+
    'if,'+
    'import,'+
    'in,'+
    'include,'+
    'interface,'+
    'is,'+
    'isnot,'+
    'iterator,'+
    'let,'+
    'macro,'+
    'method,'+
    'mixin,'+
    'mod,'+
    'nil,'+
    'not,'+
    'notin,'+
    'object,'+
    'of,'+
    'or,'+
    'out,'+
    'proc,'+
    'ptr,'+
    'raise,'+
    'ref,'+
    'return,'+
    'shl,'+
    'shr,'+
    'static,'+
    'template,'+
    'try,'+
    'tuple,'+
    'type,'+
    'using,'+
    'var,'+
    'when,'+
    'while,'+
    'xor,'+
    'yield'
;

  sNimTypes =
  'integer,'+
  'string,'+
  'boolean,'+
  'char';

  sNimFunctions =
    'echo';

