{**
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey
 *}

{
  ref:
}

  sPyKeywords =
    'async,'+
    'and,'+
    'assert,'+
    'as,'+
    'break,'+
    'class,'+
    'continue,'+
    'def,'+
    'del,'+
    'elif,'+
    'else,'+
    'except,'+
    'exec,'+
    'finally,'+
    'for,'+
    'from,'+
    'global,'+
    'nonlocal'+
    'if,'+
    'import,'+
    'in,'+
    'is,'+
    'lambda,'+
    'not,'+
    'divmod,'+
    'or,'+
    'pass,'+
    'print,'+
    'raise,'+
    'return,'+
    'try,'+
    'while,'+
    'wait,'+
    'with,'+
    'yield';

  sPyTypes =
    'chr,'+
    'float,'+
    'tuple,'+
    'type,'+
    'unichr,'+
    'int,'+
    'long,'+
    'dict,'+
    'unicode';

  sPyValues =
    'False,'+
    'oct,'+
    'None,'+
    'file,'+
    'True';

  sPyFunctions =
    '__future__,'+
    '__import__,'+
    'abs,'+
    'apply,'+
    'buffer,'+
    'callable,'+
    'cmp,'+
    'coerce,'+
    'compile,'+
    'complex,'+
    'delattr,'+
    'dir,'+
    'eval,'+
    'execfile,'+
    'filter,'+
    'getattr,'+
    'globals,'+
    'hasattr,'+
    'hash,'+
    'help,'+
    'hex,'+
    'id,'+
    'input,'+
    'intern,'+
    'isinstance,'+
    'issubclass,'+
    'iter,'+
    'len,'+
    'list,'+
    'locals,'+
    'NotImplemented,'+
    'map,'+
    'max,'+
    'min,'+
    'open,'+
    'ord,'+
    'pow,'+
    'range,'+
    'raw_input,'+
    'reduce,'+
    'reload,'+
    'repr,'+
    'round,'+
    'self,'+
    'setattr,'+
    'slice,'+
    'str,'+
    'vars,'+
    'xrange,'+
    'zip';
